### ISSUE TITLE
Heeelp 

### ISSUE THREAD

**Issue by zJeffGamer** [berkayylmao/setting-up-sbrw#12]
org.wildfly.swarm.bootstrap.util.TempFileManager$1.visitFile(TempFileManager.java:100)
2023-05-03 14:03:21,717 ERROR [stderr] (main)   at java.base/java.nio.file.Files.walkFileTree(Files.java:2725)
2023-05-03 14:03:21,717 ERROR [stderr] (main)   at java.base/java.nio.file.Files.walkFileTree(Files.java:2797)
2023-05-03 14:03:21,718 ERROR [stderr] (main)   at org.wildfly.swarm.bootstrap.util.TempFileManager.deleteRecursively(TempFileManager.java:100)
2023-05-03 14:03:21,720 ERROR [stderr] (main)   at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4696)
2023-05-03 14:03:21,721 ERROR [stderr] (main)   at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5581)
2023-05-03 14:03:21,725 ERROR [stderr] (main)   at org.wildfly.swarm.bootstrap.util.TempFileManager.close(TempFileManager.java:90)
2023-05-03 14:03:21,725 ERROR [stderr] (main)   at org.wildfly.swarm.container:runtime@2.6.0.Final//org.wildfly.swarm.container.runtime.RuntimeServer.cleanup(RuntimeServer.java:323)
2023-05-03 14:03:21,726 ERROR [stderr] (main)   at org.wildfly.swarm.container:runtime@2.6.0.Final//org.wildfly.swarm.container.runtime.RuntimeServer.stop(RuntimeServer.java:313)
2023-05-03 14:03:21,726 ERROR [stderr] (main)   at org.wildfly.swarm.container:runtime@2.6.0.Final//org.wildfly.swarm.container.runtime.RuntimeServer$Proxy$_$$_WeldClientProxy.stop(Unknown Source)
2023-05-03 14:03:21,726 ERROR [stderr] (main)   at org.wildfly.swarm.container:api@2.6.0.Final//org.wildfly.swarm.Swarm.stop(Swarm.java:434)
2023-05-03 14:03:21,727 ERROR [stderr] (main)   at org.wildfly.swarm.container:api@2.6.0.Final//org.wildfly.swarm.Swarm.tryToStopAfterStartupError(Swarm.java:779)
2023-05-03 14:03:21,727 ERROR [stderr] (main)   at org.wildfly.swarm.container:api@2.6.0.Final//org.wildfly.swarm.Swarm.main(Swarm.java:756)
2023-05-03 14:03:21,727 ERROR [stderr] (main)   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-05-03 14:03:21,728 ERROR [stderr] (main)   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-05-03 14:03:21,728 ERROR [stderr] (main)   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-05-03 14:03:21,729 ERROR [stderr] (main)   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2023-05-03 14:03:21,729 ERROR [stderr] (main)   at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:57)
2023-05-03 14:03:21,729 ERROR [stderr] (main)   at org.wildfly.swarm.bootstrap.Main.run(Main.java:134)
2023-05-03 14:03:21,730 ERROR [stderr] (main)   at org.wildfly.swarm.bootstrap.Main.main(Main.java:87)
2023-05-03 14:03:21,731 ERROR [stderr] (main) java.nio.file.FileSystemException: C:\Users\Jeff\AppData\Local\Temp\thorntailnarayana-jts-idlj-5.9.8.Final5320675149778258534.jar: O arquivo jß estß sendo usado por outro processo.
2023-05-03 14:03:21,731 ERROR [stderr] (main)

 heeelp

**Comment by zilinkids** [comment]
Download a new Redis, but if you don't need to use the friend system, you can disable this option in the database, so the server won't report an error.
